#!/bin/bash
[[ ! -z $1 ]] && [[ $1 = "-v" ]] && verbose=1

log(){
    [[ $verbose = 1 ]] && "$@" || "$@" 1> /dev/null
}

# If this is our first run, save a copy of the system's original hosts file and set to read-only for safety
if [ ! -f /etc/hosts-system ]
then
 log echo "Saving copy of system's original hosts file..."
 cp /etc/hosts /etc/hosts-system
 chmod 444 /etc/hosts-system
fi

# Perform work in temporary files
temphosts1=`mktemp`
temphosts2=`mktemp`

# Obtain various hosts files and merge into one
log echo "Downloading ad-blocking hosts files..."
wget -qnv -O - http://winhelp2002.mvps.org/hosts.txt >> $temphosts1
wget -qnv -O - http://someonewhocares.org/hosts/hosts >> $temphosts1
wget -qnv -O - "http://pgl.yoyo.org/as/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext" >> $temphosts1

# Do some work on the file:
# 1. Remove MS-DOS carriage returns
# 2. Delete all lines that don't begin with 127.0.0.1
# 3. Delete any lines containing the word localhost because we'll obtain that from the original hosts file
# 4. Delete any lines containing the word dropbox.com.
# 5. Replace 127.0.0.1 with 0.0.0.0 because then we don't have to wait for the resolver to fail
# 6. Scrunch extraneous spaces separating address from name into a single tab
# 7. Delete any comments on lines
# 8. Clean up leftover trailing blanks
# Pass all this through sort with the unique flag to remove duplicates and save the result
log echo "Parsing, cleaning, de-duplicating, sorting..."

sed -e 's/\r//' -e '/^127.0.0.1/!d' -e '/localhost/d' -e '/dropbox.com/d' -e 's/127.0.0.1/0.0.0.0/' -e 's/ \+/\t/' -e 's/#.*$//' -e 's/[ \t]*$//' < $temphosts1 | sort -u > $temphosts2

# Combine system hosts with adblocks
log echo Merging with original system hosts...
log echo -e "\n# Ad blocking hosts generated "`date` | cat /etc/hosts-system - $temphosts2 > /etc/hosts

# Clean up temp files and remind user to copy new file
log echo "Cleaning up..."
rm $temphosts1 $temphosts2
log echo "Done."
log echo
log echo "You can always restore your original hosts file with this command:"
log echo "cp /etc/hosts-system /etc/hosts"
log echo "so don't delete that file! (It's saved read-only for your protection.)"
