#!/bin/bash
# author: Lukas Kluft
# version: 30.01.2016
#
# note: This script is a "cleaner" version of a script published on
# https://www.kubuntuforums.net/showthread.php?56419-Script-to-automate-building-an-adblocking-hosts-file
#
# purpose: generate /etc/hosts file to block ads.

# check if run as root/sudo
[[ $(whoami) == 'root' ]] || { echo 'ERROR: run as root'; exit 1 ; }

# control verbosity
[[ $1 == "-v" ]] && verbose=1
log() {
    [[ "${verbose}" == 1 ]] && echo "$@"
}

# If this is our first run, save a copy of the system's original hosts file and
# set to read-only for safety.
if [[ ! -f /etc/hosts-system ]]; then
 log "Saving copy of system's original hosts file..."
 cp /etc/hosts /etc/hosts-system
 chmod 444 /etc/hosts-system
fi

# Perform work in temporary files
tmphosts="$(mktemp --tmpdir gethosts.XXXXXXXX)"

# Obtain various hosts files and merge into one
log "Downloading ad-blocking hosts files..."
wget -qnv -O "${tmphosts}" \
'http://adaway.org/hosts.txt' \
'http://hosts-file.net/ad_servers.asp' \
'http://hosts-file.net/download/hosts.txt' \
'http://hosts-file.net/hphosts-partial.txt'\
'http://pgl.yoyo.org/as/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext' \
'http://someonewhocares.org/hosts/hosts' \
'http://winhelp2002.mvps.org/hosts.txt' \
'http://www.malwaredomainlist.com/hostslist/hosts.txt'

# Do some work on the file:
# 1. Remove MS-DOS carriage returns
# 2. Delete all lines that don't begin with 127.0.0.1
# 3. Delete any lines containing the word localhost because we'll obtain that
#    from the original hosts file
# 4. Delete any lines containing the word dropbox.com.
# 5. Replace 127.0.0.1 with 0.0.0.0 because then we don't have to wait for the
#    resolver to fail
# 6. Scrunch extraneous spaces separating address from name into a single tab
# 7. Delete any comments on lines
# 8. Clean up leftover trailing blanks
# Sort the output and delete duplicates.
log "Parsing, cleaning, de-duplicating, sorting..."

sed -e 's/\r//' \
    -e '/^127.0.0.1/!d' \
    -e '/localhost/d' \
    -e '/dropbox.com/d' \
    -e 's/127.0.0.1/0.0.0.0/' \
    -e 's/ \+/\t/' \
    -e 's/#.*$//' \
    -e 's/[ \t]*$//' \
    "${tmphosts}" | sort -u -o "${tmphosts}"

# Combine system hosts with adblocks and current date
log "Merging with original system hosts..."
echo -e "\n# Ad blocking hosts generated $(date)" \
  | cat /etc/hosts-system - "${tmphosts}" > /etc/hosts

# Clean up temp files and remind user to copy new file
log "Cleaning up..." && rm "${tmphosts}" && log "Done."

# Print information how to restore original hosts file
log "You can always restore your original hosts file with this command:"
log "cp /etc/hosts-system /etc/hosts"
log "so don't delete that file! (It's saved read-only for your protection.)"
