#!/bin/bash
# author: Lukas Kluft
# version: 29.10.2015
#
# purpose: pull all git repositories

blue='\033[1;34m'
white='\033[0m'

for gitdir in $HOME/git/*
    do
    if [[ "$gitdir" != *".git" ]];then
        cd $gitdir
        echo -e Aktuelles Verzeichnis: $blue$(pwd)$white
        git pull
    fi
    done
