#!/bin/bash

USERNAME=$USER
REMOTEHOST='thunder7'

if [[ $1 = -u ]]
then
    umount t7data
    umount u300509
    umount lkluft
else
    OPTIONS='auto_cache,reconnect,follow_symlinks,noappledouble'
    sshfs -r -o $OPTIONS,volname=t7data \
        "${USERNAME}@${REMOTEHOST}":/scratch/uni/u237/data \
        "${HOME}/t7data"
    sshfs -o $OPTIONS,volname=u300509 \
        "${USERNAME}@${REMOTEHOST}": \
        "${HOME}/u300509"
    sshfs -o $OPTIONS,volname=lkluft \
        "${USERNAME}@${REMOTEHOST}":/scratch/uni/u237/users/lkluft \
        "${HOME}/lkluft"
fi

