#!/bin/bash
# author: Lukas Kluft
# version: 23.07.2014
#
# purpose: convert a list of ppm-files to
#           pdf-format

# check if path to inputfile(s) is given
if [ -z "$*" ] || [[ $* == "-r" ]];then
    echo "ERROR: No input-files."
    echo "USAGE: ppmtopdf [-r] PATH/TO/FILES"
    exit
fi

# convert all given files
for i in $@
    do
    if [ "$i" != "-r" ];then
        if [ "${i#*.}" == "ppm" ];then
            convert $i ${i%.ppm}.pdf
            # delete input-files if -r parameter is given
            if [[ $1 == "-r" ]];then
                rm -- $i
            fi
            rename -- 's/-//g' ${i%.ppm}.pdf
        else
        echo ERROR: $i is no ppm-file.
        fi
    fi
done
