#!/bin/bash
# author: Lukas Kluft
# version: 29.03.2015
#
# purpose: install scientific python modules in a virtual environment

# check if a virtualenv is activated
[[ -z $VIRTUAL_ENV ]] && echo ERROR: No virtualenv activated. && exit 1

# install libraries needed by some modules
sudo apt-get install -y \
    python-dev                  `# NumPy` \
    tcl-dev tk-dev              `# matplotlib` \
    liblapack-dev gfortran      `# SciPy` \
    libhdf5-dev libnetcdf-dev   `# netCDF4` \
    libgeos-dev libproj-dev     `# cartopy`

# link site-packages needed for matplotlib
ln -sf /usr/lib/python2.7/dist-packages/{glib,gobject,cairo,gtk-2.0,pygtk.py,pygtk.pth} \
    $VIRTUAL_ENV/lib/python2.7/site-packages

# upgrade setuptools and pip to the latest version
pip install -U setuptools pip

# IPython: enhanced python shell
pip install ipython
# IPython Notebook: modules required for IPython Notebook
pip install pyzmq pygments mistune jinja2 tornado jsonschema

# NumPy: mathematical classes and functions
pip install numpy

# matplotlib: object-oriented plotting library
pip install matplotlib

# SciPy: scientific computing package
pip install scipy

# netCDF4: interface to the netCDF version 4 library
pip install netCDF4

# cartopy: drawing maps
pip install cython && pip install shapely pyshp cartopy

# skewt: skew-T log-p diagrams for radiosonde soundings
pip install skewt

