#!/bin/bash
# author: Lukas Kluft
# version: 07.10.2015
#
# purpose: set random picture as background image

# exit if DISPLAY is not set
[[ -z $DISPLAY ]] && exit 1

# set directory conatining the pictures
DIR="/usr/share/backgrounds"

# get random picture
PIC=$(find $DIR -type f | shuf -n 1)

# set dbus session. this enables cron to change the background:
# * * * * DISPLAY=:0 /path/to/shuffle_background
PID=$(pgrep gnome-session)
export DBUS_SESSION_BUS_ADDRESS=$(grep -z DBUS_SESSION_BUS_ADDRESS /proc/$PID/environ|cut -d= -f2-)

# set picture as background image
gsettings set org.gnome.desktop.background picture-uri file://$PIC
