#!/bin/bash
# author: Lukas Kluft
# version: 26.08.2015
#
# purpose: update current or all conda environments

if [[ $1 == "--all" || $1 == "-a" ]]; then
    # get current environment
    initial_env=$(conda env list | grep \* | cut -d " " -f 1)

    # update all environments
    for env in $(conda info --envs | sed /^[#]/d | cut -d " " -f 1)
    do
        source activate $env
        conda update -y --all
        conda clean -y -p
        conda clean -y -t
    done

    # activate initial environment
    echo source activate $initial_env
else
        conda update -y --all
        conda clean -y -p
        conda clean -y -t
fi

