#!/bin/bash
# author: Lukas Kluft
# version: 28.08.2015
#
# purpose: update current or all conda environments

# check if conda is installed
hash conda &> /dev/null || exit 1

if [[ $1 == "--all" || $1 == "-a" ]]; then
    # update all environments
    for env in $(conda info --envs | sed /^[#]/d | cut -d " " -f 1)
    do
        conda update -n $env -y --all
    done
else
    # updated current environment
    conda update -y --all
fi

# clean unused packages and tarballs
conda clean -pty
