#!/bin/bash
# author: Lukas Kluft
# version: 08.01.2016
#
# purpose: 1) update and build ARTS binary
#          2) create ctags file
#          3) update arts-xml-data
#        [ 4) run update-vim-arts-syntax ]

# user settings
ARTS_DIR='/scratch/uni/u237/users/lkluft/arts'
ARTS_XML='/scratch/uni/u237/users/lkluft/arts-xml-data'
NCORES=8

# change to ARTS directory
cd "${ARTS_DIR}"

# check if revision number has changed
if [[ "$(svn info -r HEAD | grep ^Rev)" == "$(svn info | grep ^Rev)" ]];then
    echo 'Up to date.'
else
    # update and build ARTS
    svn update && cd build && make -j"${NCORES}" arts

    # create (c)tags file for vim
    cd "${ARTS_DIR}" && ctags -R

    # update arts-xml-data
    cd "${ARTS_XML}" && svn update

    # if in PATH, run update-vim-arts-syntax
    hash update-vim-arts-syntax &> /dev/null && update-vim-arts-syntax
fi
