#!/bin/bash
# author: Lukas Kluft
# version: 30.01.2015
#
# purpose: automatically update the system

# set PATH (necessary if run as cron job)
PATH="$PATH:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin"

# verbose mode
if [[ ! -z $1 && "$1" -eq "-v" ]];then
    v=1
fi

log(){
    [[ $v -eq 1 ]] && "$@" || "$@" 1> /dev/null
}

# update package list
log echo -e "\t#### Update package list ####\n"
log sudo apt-get update

# install new packages
log echo -e "\n\n\t#### Install new packages ####\n"
log sudo apt-get -y dist-upgrade

# clean up
log echo -e "\n\n\t#### Remove old downloaded archive files ####\n"
log sudo apt-get autoclean

log echo -e "\n\n\t#### Remove unused packages ####\n"
log sudo apt-get -y autoremove

# if existing, remove unused configuration files
if [[ $(dpkg --list | grep ^rc | cut -d " " -f 3) ]];then
    log echo -e "\n\n\t#### Remove unused configuration files ####\n"
    log sudo dpkg --purge $(dpkg --list | grep ^rc | cut -d " " -f 3)
fi

exit 0
