#!/bin/bash
# author: Lukas Kluft
# version: 04.05.2015
#
# purpose: automatically update the system

# check if run as root/sudo
[[ $(whoami) == 'root' ]] || { echo 'ERROR: run as root'; exit 1 ; }

# verbose mode
[[ ! -z $1 && "$1" -eq "-v" ]] && v=1

log(){ [[ $v -eq 1 ]] && "$@" || "$@" 1> /dev/null ; }


# update package list
log echo -e "\t#### Update package list ####\n"
log sudo apt-get update

# install new packages
log echo -e "\n\n\t#### Install new packages ####\n"
log sudo DEBIAN_FRONTEND=noninteractive apt-get -y dist-upgrade

# clean up
log echo -e "\n\n\t#### Remove old downloaded archive files ####\n"
log sudo apt-get autoclean

log echo -e "\n\n\t#### Remove unused packages ####\n"
log sudo DEBIAN_FRONTEND=noninteractive apt-get -y autoremove

# if existing, remove unused configuration files
if [[ $(dpkg --list | grep ^rc | cut -d " " -f 3) ]];then
    log echo -e "\n\n\t#### Remove unused configuration files ####\n"
    log sudo dpkg --purge $(dpkg --list | grep ^rc | cut -d " " -f 3)
fi

exit 0

