#!/bin/bash
# author: Lukas Kluft
# version: 17.10.2014
#
# purpose: automatocally update the system

# update package list
echo -e "Update package list\n"
sudo apt-get -y update

# upgrade all packages
echo -e "\n\nUpdate packages\n"
sudo apt-get -y dist-upgrade

# clean up
echo -e "\n\nClean up\n"
sudo apt-get autoclean
sudo apt-get -y autoremove

if [[ $(dpkg --list | grep ^rc | cut -d " " -f 3) ]];then
    echo -e "\n\nRemove unused configuration files\n"
    sudo dpkg --purge $(dpkg --list | grep ^rc | cut -d " " -f 3)
fi

exit 0
