#!/bin/bash
# author: Lukas Kluft
# version: 29.03.2014
# 
# purpose: download and display the current weather in given city.
# multiple locations are possible

# check if location is given. otherwise error
if [ -z "$1" ]; then
    echo Bitte Stadtname angeben
    exit
fi

# download current weather information
wget --timeout=2 http://www.wetteronline.de/wetter/"$1" &> /dev/null

# check if download suceeded
if [ -f "$1" ]; then
    # filter temperature and weather information
    temp=$(grep "current-weather" "$1" | cut -d ">" -f 5 | cut -d "<" -f 1)
    aktuell=$(grep "current-weather" "$1" | cut -d '"' -f 8)
    # check if weather information is existing
    if [ -z "$aktuell" ]; then
        echo Keine Wetterinformationen für $1 gefunden
    else
        echo Wetter  in "$1" $(echo $temp und $aktuell | sed 's/&deg;/°/g' | sed 's/&ouml;/ö/g')
    fi
    #rm "$1"
fi

# if several locations are given run script recursively
if [ ! -z $2 ]; then
    for ((n=2;n<=$#;n++))
    do
    wetter ${!n}
    done
fi
